[project]
name = "iaia-lab04"
version = "0.1.0"
description = "Laboratorio 04: Perceptrón y Aprendizaje con Descenso de Gradiente"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter",
    "pandas==3.0.1",
    "seaborn==0.13.2",
    "matplotlib==3.10.8",
    "numpy==2.4.2",
    "tensorflow>=2.18.0",
]
